// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gw61dpWNYYTDUaRVcO13_U7hrzi4Cic',
    appId: '1:622621114175:web:def600d690c18cbc841d8a',
    messagingSenderId: '622621114175',
    projectId: 'whatsapp-13467',
    authDomain: 'whatsapp-13467.firebaseapp.com',
    storageBucket: 'whatsapp-13467.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1HAUrRR-LxuXt3mYiY0KqugmbRnsT3k0',
    appId: '1:622621114175:android:b00300123f0f11f0841d8a',
    messagingSenderId: '622621114175',
    projectId: 'whatsapp-13467',
    storageBucket: 'whatsapp-13467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRhu-ppNU4bIo0kavio7bETFwI6KtplU',
    appId: '1:622621114175:ios:0e01d9a710d41f95841d8a',
    messagingSenderId: '622621114175',
    projectId: 'whatsapp-13467',
    storageBucket: 'whatsapp-13467.appspot.com',
    androidClientId: '622621114175-pvjr7fh584498gk65p59qrtefj098a6v.apps.googleusercontent.com',
    iosClientId: '622621114175-55duhgfvag7487a3aarfv0f87khj85uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappcloneflutter',
  );
}
